### ISSUE TITLE
HTMLCollection as target in constructor breaks it

### ISSUE THREAD

**Issue by ZRdesign** [rkusa/selector-observer#5]
#6  
` 
 this.targets = targets instanceof NodeList 
                   ? Array.prototype.slice.call(targets)
                   : [targets]
`
If constructor gets a HTMLCollection for `targets` argument then it gets handled like single element and wraps it in Array

**Comment by rkusa** [comment]
Fixed in #6, thanks @ZRdesign

**Comment by ZRdesign** [comment]
With pleasure! 👍 
Could you update the npm package in exchange please :)
